# Site settings
title: Dr. Esteban Garzón
email: esteban.garzon@unical.it
description: Personal Website of Esteban Garzón
baseurl: ""
url: ""
affiliation: I'm with the <a href="https://dimes.unical.it" target="_blank">Department of Computer Engineering, Modeling, Electronics and Systems</a> at the University of Calabria

# Google analytics ID
#google_analytics: UA-176412042-1

# Location info. (shown in footer)
location: >
  Address: <br/>
  Building 42C 2nd-Floor <br/>
  University of Calabria <br/>
  Via P. Bucci <br/>
  Rende (CS) 87036<br/>

# Contact info. (shown in footer)
contact: >
    Contact Esteban via email: <a href="mailto:esteban.garzon@unical.it" target="_blank">esteban.garzon@unical.it</a> <br/>    

#<br/><a href="/aboutwebsite.html">Use this webpage as a template for your own!</a>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: research
    title: Research
    children:
      - title: "Research & Funding"
        url: "/research/"
      - title: "PIMAT Project"
        url: "/proj-pimat/"
  - name: publications
  - name: talks
  - name: tapeouts
  - name: teaching
  - name: service
# - name: software
# - name: team

# Do you want to group your publications by year? {true/false}
group_pub_by_year: true

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
